puts "Creating fruits..."
orange = Food.create(name: "orange", category: "fruits", to_avoid: false)
citron = Food.create(name: "citron", category: "fruits", to_avoid: false)
pamplemousse = Food.create(name: "pamplemousse", category: "fruits", to_avoid: false)
clementine = Food.create(name: "clémentine", category: "fruits", to_avoid: false)
ananas = Food.create(name: "ananas", category: "fruits", to_avoid: false)
banane = Food.create(name: "banane", category: "fruits", to_avoid: false)
passion = Food.create(name: "fruits de la passion", category: "fruits", to_avoid: false)
fraise = Food.create(name: "fraise", category: "fruits", to_avoid: false)
framboise = Food.create(name: "framboise", category: "fruits", to_avoid: false)
canneberge = Food.create(name: "canneberge", category: "fruits", to_avoid: false)
groseille = Food.create(name: "groseille", category: "fruits", to_avoid: false)
kiwi = Food.create(name: "kiwi", category: "fruits", to_avoid: false)
raisin = Food.create(name: "raisin", category: "fruits", to_avoid: false)

puts "Creating légumes..."
pomme_de_terre = Food.create(name: "pomme de terre", category: "légumes", to_avoid: false)
patate_douce = Food.create(name: "patate douce", category: "légumes", to_avoid: false)
panais = Food.create(name: "panais", category: "légumes", to_avoid: false)
salade = Food.create(name: "salade", category: "légumes", to_avoid: false)
laitue = Food.create(name: "laitue", category: "légumes", to_avoid: false)
cresson = Food.create(name: "cresson", category: "légumes", to_avoid: false)
mache = Food.create(name: "mâche", category: "légumes", to_avoid: false)
endives = Food.create(name: "endives", category: "légumes", to_avoid: false)
choux = Food.create(name: "choux", category: "légumes", to_avoid: false)
poireaux = Food.create(name: "poireaux", category: "légumes", to_avoid: false)
tomates = Food.create(name: "tomates", category: "légumes", to_avoid: false)
carottes = Food.create(name: "carottes", category: "légumes", to_avoid: false)
courgettes = Food.create(name: "courgettes", category: "légumes", to_avoid: false)
épinards = Food.create(name: "épinards", category: "légumes", to_avoid: false)
fèves = Food.create(name: "fèves", category: "légumes", to_avoid: false)
haricots = Food.create(name: "haricots", category: "légumes", to_avoid: false)

puts "Creating produits laitiers pauvres en lactose..."
laitages_sans_lactose = Food.create(name: "laitages sans lactose", category: "produits laitiers pauvres en lactose", to_avoid: false)
laits_végétaux = Food.create(name: "laits végétaux", category: "produits laitiers pauvres en lactose", to_avoid: false)
cheddar = Food.create(name: "cheddar", category: "produits laitiers pauvres en lactose", to_avoid: false)
parmesan = Food.create(name: "parmesan", category: "produits laitiers pauvres en lactose", to_avoid: false)
gouda = Food.create(name: "gouda", category: "produits laitiers pauvres en lactose", to_avoid: false)
fromages_brebis = Food.create(name: "fromages de brebis", category: "produits laitiers pauvres en lactose", to_avoid: false)
laitages_brebis = Food.create(name: "laitages de brebis", category: "produits laitiers pauvres en lactose", to_avoid: false)
yaourt_soja, = Food.create(name: "yaourts à base de lait de soja,", category: "produits laitiers pauvres en lactose", to_avoid: false)
creme_fouettee = Food.create(name: "Crème fouettée", category: "produits laitiers pauvres en lactose", to_avoid: false)
creme_coco = Food.create(name: "Crème de coco", category: "produits laitiers pauvres en lactose", to_avoid: false)

puts "Creating céréales..."
pain_levain = Food.create(name: "pain au levain", category: "céréales", to_avoid: false)
pain_sans_gluten = Food.create(name: "pain sans gluten", category: "céréales", to_avoid: false)
quinoa = Food.create(name: "quinoa", category: "céréales", to_avoid: false)
riz = Food.create(name: "riz", category: "céréales", to_avoid: false)
mais = Food.create(name: "maïs", category: "céréales", to_avoid: false)
sarrasin = Food.create(name: "sarrasin", category: "céréales", to_avoid: false)
millet = Food.create(name: "millet", category: "céréales", to_avoid: false)
sorgho = Food.create(name: "sorgho", category: "céréales", to_avoid: false)
farine_avoine = Food.create(name: "farine d'avoine", category: "céréales", to_avoid: false)
tortilla = Food.create(name: "tortilla", category: "céréales", to_avoid: false)
maizena = Food.create(name: "maïzena", category: "céréales", to_avoid: false)
polenta = Food.create(name: "polenta", category: "céréales", to_avoid: false)
galettes_riz = Food.create(name: "galettes de riz", category: "céréales", to_avoid: false)
pâtes_riz = Food.create(name: "pâtes de riz", category: "céréales", to_avoid: false)

puts "Creating sucres..."
sucre_blanc = Food.create(name: "sucre blanc", category: "sucres", to_avoid: false)
cassonade = Food.create(name: "cassonade", category: "sucres", to_avoid: false)
confiture_sans_fructose = Food.create(name: "confiture sans fructose", category: "sucres", to_avoid: false)
sirop_erable = Food.create(name: "sirop d'érable", category: "sucres", to_avoid: false)
chocolat = Food.create(name: "chocolat", category: "sucres", to_avoid: false)
sucralose = Food.create(name: "sucralose", category: "sucres", to_avoid: false)

puts "Creating autres..."
viande = Food.create(name: "viande", category: "autres", to_avoid: false)
volaille = Food.create(name: "volaille", category: "autres", to_avoid: false)
poisson = Food.create(name: "poisson", category: "autres", to_avoid: false)
tofu = Food.create(name: "tofu", category: "autres", to_avoid: false)
oleagineux = Food.create(name: "oléagineux sauf cajou et pistaches", category: "autres", to_avoid: false)
the = Food.create(name: "thé", category: "autres", to_avoid: false)
tisanes = Food.create(name: "tisanes", category: "autres", to_avoid: false)
epices = Food.create(name: "épices", category: "autres", to_avoid: false)
condiments = Food.create(name: "condiments", category: "autres", to_avoid: false)
huiles_vegetales = Food.create(name: "huiles végétales", category: "autres", to_avoid: false)

puts "Creating fructanes..."
melon = Food.create(name: "melon", category: "fructanes", to_avoid: true)
peche = Food.create(name: "pêche", category: "fructanes", to_avoid: true)
brugnon = Food.create(name: "brugnon", category: "fructanes", to_avoid: true)
abricot = Food.create(name: "abricot", category: "fructanes", to_avoid: true)
nectarine = Food.create(name: "nectarine", category: "fructanes", to_avoid: true)
figue = Food.create(name: "figue", category: "fructanes", to_avoid: true)
datte = Food.create(name: "datte", category: "fructanes", to_avoid: true)
pruneaux = Food.create(name: "pruneaux", category: "fructanes", to_avoid: true)
grenade = Food.create(name: "grenade", category: "fructanes", to_avoid: true)
ail = Food.create(name: "ail", category: "fructanes", to_avoid: true)
oignon = Food.create(name: "oignon", category: "fructanes", to_avoid: true)
echalote = Food.create(name: "échalote", category: "fructanes", to_avoid: true)
vert_poireau = Food.create(name: "vert du poireau", category: "fructanes", to_avoid: true)
champignon = Food.create(name: "champignon", category: "fructanes", to_avoid: true)
salsifis = Food.create(name: "salsifis", category: "fructanes", to_avoid: true)
choux_bruxelles = Food.create(name: "choux de Bruxelles", category: "fructanes", to_avoid: true)
ble = Food.create(name: "produits céréaliers à base de blé", category: "fructanes", to_avoid: true)
orge = Food.create(name: "Produits céréaliers à base d'orge", category: "fructanes", to_avoid: true)
pates = Food.create(name: "pâtes", category: "fructanes", to_avoid: true)
couscous = Food.create(name: "couscous", category: "fructanes", to_avoid: true)
barres_cereales = Food.create(name: "barres de céréales et biscuits contenant des agents sucrants", category: "fructanes", to_avoid: true)

puts "Creating galactans..."
courge = Food.create(name: "courge", category: "galactans", to_avoid: true)
betterave = Food.create(name: "betterave", category: "galactans", to_avoid: true)
pois = Food.create(name: "pois", category: "galactans", to_avoid: true)
noix_cajou = Food.create(name: "noix de cajou", category: "galactans", to_avoid: true)
pistaches = Food.create(name: "pistaches", category: "galactans", to_avoid: true)
legumineuses = Food.create(name: "légumineuses", category: "galactans", to_avoid: true)
soja = Food.create(name: "soja", category: "galactans", to_avoid: true)
cacao = Food.create(name: "cacao consommé en grande quantité", category: "galactans", to_avoid: true)
houmous = Food.create(name: "houmous", category: "galactans", to_avoid: true)
tzatziki = Food.create(name: "tzatziki", category: "galactans", to_avoid: true)
ketchup = Food.create(name: "ketchup", category: "galactans", to_avoid: true)
pesto = Food.create(name: "pesto", category: "galactans", to_avoid: true)
sauces = Food.create(name: "sauces et épices contenant de l'ail et de l'oignon", category: "galactans", to_avoid: true)

puts "Creating fructose..."
cerise = Food.create(name: "cerise", category: "fructose", to_avoid: true)
tomate_sechee = Food.create(name: "tomate séchée", category: "fructose", to_avoid: true)
tomate_concentre = Food.create(name: "tomate en concentré", category: "fructose", to_avoid: true)
coing = Food.create(name: "coing", category: "fructose", to_avoid: true)
goyave = Food.create(name: "goyave", category: "fructose", to_avoid: true)
mangue = Food.create(name: "mangue", category: "fructose", to_avoid: true)
pomme = Food.create(name: "pomme", category: "fructose", to_avoid: true)
poire = Food.create(name: "poire", category: "fructose", to_avoid: true)
nectars = Food.create(name: "nectars de fruits", category: "fructose", to_avoid: true)
fruits_conserve = Food.create(name: "fruits en conserve", category: "fructose", to_avoid: true)
confitures = Food.create(name: "confitures classiques", category: "fructose", to_avoid: true)
asperge = Food.create(name: "asperge", category: "fructose", to_avoid: true)
coeur_artichaut, = Food.create(name: "coeur d'artichaut,", category: "fructose", to_avoid: true)
miel = Food.create(name: "miel", category: "fructose", to_avoid: true)
fructose = Food.create(name: "fructose", category: "fructose", to_avoid: true)
vin = Food.create(name: "vins liquoreux", category: "fructose", to_avoid: true)
rhum = Food.create(name: "rhum", category: "fructose", to_avoid: true)
liqueur = Food.create(name: "liqueur", category: "fructose", to_avoid: true)
porto = Food.create(name: "porto", category: "fructose", to_avoid: true)

puts "Creating disaccharides..."
laits_vache = Food.create(name: "laits de vache", category: "disaccharides", to_avoid: true)
laits_chèvre = Food.create(name: "laits de chèvre", category: "disaccharides", to_avoid: true)
fromage_frais = Food.create(name: "fromages frais", category: "disaccharides", to_avoid: true)
creme_traditionnelle = Food.create(name: "crème traditionnelle", category: "disaccharides", to_avoid: true)
yaourt = Food.create(name: "yaourts classiques", category: "disaccharides", to_avoid: true)

puts "Creating polyols..."
avocat = Food.create(name: "avocat", category: "polyols", to_avoid: true)
cassis = Food.create(name: "cassis", category: "polyols", to_avoid: true)
mure = Food.create(name: "mûre", category: "polyols", to_avoid: true)
prune = Food.create(name: "prune", category: "polyols", to_avoid: true)
coco = Food.create(name: "noix de coco", category: "polyols", to_avoid: true)
chou_fleur = Food.create(name: "chou-fleur", category: "polyols", to_avoid: true)
chewing_gum = Food.create(name: "chewing gum", category: "polyols", to_avoid: true)
bonbons = Food.create(name: "bonbons", category: "polyols", to_avoid: true)
chocolat_sucre = Food.create(name: "chocolat sucré", category: "polyols", to_avoid: true)
sorbitol = Food.create(name: "sorbitol", category: "polyols", to_avoid: true)
mannitol = Food.create(name: "mannitol", category: "polyols", to_avoid: true)
xylitol = Food.create(name: "xylitol", category: "polyols", to_avoid: true)
isomalt = Food.create(name: "isomalt", category: "polyols", to_avoid: true)
lactilol = Food.create(name: "lactilol", category: "polyols", to_avoid: true)
erythritol = Food.create(name: "érythritol", category: "polyols", to_avoid: true)
polydextrose = Food.create(name: "polydextrose", category: "polyols", to_avoid: true)

paille = Food.create(name: "boissons prises à la paille", category: "autres", to_avoid: true)
repas_rapides = Food.create(name: "repas trop rapides", category: "polyols", to_avoid: true)

puts "Finished!"
